# Generated by Django 3.2.6 on 2021-08-12 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Hitokoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=20)),
                ('posted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
