# Generated by Django 3.2.6 on 2021-08-12 06:55

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('Keijiban', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hitokoto',
            name='posted_at',
            field=models.DateTimeField(verbose_name=datetime.datetime(2021, 8, 12, 6, 55, 27, 892220, tzinfo=utc)),
        ),
    ]
